name:                process-children
version:             0.1.0.0
github:              "TheWizardTower/process-children"
license:             BSD3
author:              "Adam McCullough"
maintainer:          "merlinfmct87@gmail.com"
copyright:           "(c) 2018 Adam McCullough"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TheWizardTower/process-children#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- optparse-applicative
- regex-base
- regex-pcre
- text

library:
  source-dirs: src

executables:
  process-children-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - process-children

tests:
  process-children-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - process-children
